src/posts/urls.py
from django.urls import path
from .views import (
    posts_home,
    posts_create,
    posts_delete,
    posts_update,
    posts_detail,

)

#app name
app_name='posts'

urlpatterns=[
    path('',posts_home,name='posts_home'),
    path('create/',posts_create,name='posts_create'),
    path('delete/<slug:slug>/',posts_delete,name='posts_delete'),
    path('update/<slug:slug>/',posts_update,name='posts_update'),
    path('detail/<slug:slug>/',posts_detail,name='posts_detail'),
]

src/src/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/',include('posts.urls'))
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
   # print(urlpatterns)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
   # print(urlpatterns)   

src/posts/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings



def upload_location(instance,filename):
    return f"images/posts/{instance.slug}/{filename}"
# Create your models here.
class Post(models.Model):
    title=models.CharField(max_length=40)
    slug=models.SlugField(unique=True,default=None)
    content=models.TextField()
    publish=models.BooleanField()
    timestamp=models.DateTimeField(auto_now=False,auto_now_add=True)
    updated=models.DateTimeField(auto_now=True,auto_now_add=False)
    image=models.ImageField(upload_to=upload_location,null=True,blank=True,height_field='height_field',width_field='width_field')
    height_field=models.IntegerField(default=0)
    width_field=models.IntegerField(default=0)
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,default=1)
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:posts_detail',kwargs={'slug':self.slug})



def create_slug(instance,new_slug=None):
    slug=slugify(instance.title)
    if new_slug is not None:
        slug=new_slug
    qs=Post.objects.filter(slug=slug).order_by('-id')
    exists=qs.exists()
    if exists:
        new_slug=f"{slug}-{qs.first().id}"
        return create_slug(instance,new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug=create_slug(instance)
    

pre_save.connect(pre_save_post_receiver,sender=Post)

src/posts/forms.py
from django.forms import ModelForm
from django import forms
from .models import(
    Post
)

class PostForm(ModelForm):
    class Meta:
        model=Post
        fields="__all__"
        exclude=['slug','height_field','width_field']

class SearchForm(forms.Form):
    query=forms.CharField(max_length=40)

src/posts/views.py
from django.shortcuts import render,get_object_or_404,reverse,redirect
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.db.models import Q
from urllib.parse import quote_plus
from django.contrib import messages
from .models import Post
from .forms import PostForm,SearchForm
# Create your views here.
def posts_home(request):
    queryset_list=Post.objects.all()
    query=request.GET.get('query') or request.POST.get('query') or None
    if query:
        print(query)
        queryset_list=queryset_list.filter(
            Q(title__icontains=query)|
            Q(content__icontains=query)|
            Q(user__first_name__icontains=query)|
            Q(user__last_name__icontains=query)
        ).distinct()
    paginator=Paginator(queryset_list,4)
    page=request.GET.get('page')
    try:
        queryset=paginator.page(page)
    except PageNotAnInteger:
        queryset=paginator.page(1)
    except EmptyPage:
        queryset=paginator.page(paginator.num_pages)
    
    contex={
        'name':'seam',
        'obj_list':queryset,
        'searched_value':query,
        'search_form':SearchForm,
    }
    return render(request,'posts/index.html',contex)

def posts_create(request):
    form=PostForm(request.POST or None,request.FILES or None)
    if request.method=='POST':
        if form.is_valid():
            form.save()
            messages.success(request,'Successfully created new post')
            return redirect(reverse('posts:posts_home'))
    context={
        'form':form
    }
    return render(request,'posts/form.html',context)

def posts_delete(request,slug=None):
    obj=get_object_or_404(Post,slug=slug)
    if request.user==obj.user:
        if request.method=="POST":
            obj.delete()
            return redirect(reverse('posts:posts_home'))
    else:
        raise Http403
    return render(request,'posts/delete.html',{"obj":obj})


def posts_update(request,slug=None):
    obj=get_object_or_404(Post,slug=slug)
    if request.method=="POST":
        form=PostForm(request.POST,request.FILES,instance=obj)
        if form.is_valid():
            obj=form.save(commit=False)
            id=obj.id
            print(obj.id )
            obj.save()
            return redirect(reverse('posts:posts_detail',kwargs={'post_id':id}))
    else:
        form=PostForm(instance=obj)
    
    context={
        'form':form
    }

    return render(request,'posts/form.html',context)

def posts_detail(request,slug=None):
    obj=get_object_or_404(Post,slug=slug)
    print(request.build_absolute_uri)
    context={
        'obj':obj,
        'share_string':quote_plus(obj.content)
    }
    return render(request,'posts/detail.html',context)

src/posts/templates/posts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>


    {%block content%} {%endblock%}
    





        <div id="fb-root"></div>
        <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.3&appId=306354656626061&autoLogAppEvents=1"></script>



        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

src/posts/templates/posts/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1> Do you really wnat to delete the post named {{obj.title}}</h1>
    <form action="." method="POST">
        {% csrf_token %}
        <input type='submit' value='delete'>
    </form>
    <a href="{% url 'posts:posts_home'%}"></a>
</body>
</html>

src/posts/templates/posts/detail.html
{% extends 'posts/base.html'%}
{%block content%} 
<div class="container">
        <h1 class="d-3">{{obj.title}}</h1>
        <div style="text-align: center;">{{obj.content}}</div>
        <img src="{%if obj.image%}{{obj.image.url}}{%endif%}" alt="" class="img-fluid">
    </div>
    <div class="jumbotron">
        <a href="{% url 'posts:posts_update' slug=obj.slug%}" class="btn btn-secondary">update</a>
        <a href="{% url 'posts:posts_delete' slug=obj.slug%}" class="btn btn-danger">delete</a>
    </div>
    <div class="p-3">
            <div class="fb-like" data-href="{{request.build_absolute_uri}}" data-width="" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
    </div>
    <div class="p-2">
            <p>Share:</p>
            <div>
                 <a href="https://www.facebook.com/sharer/sharer.php?u={{request.get_absolute_uri}}" class="btn btn-outline-success">
                     Facebook
                 </a>
                 <a href="https://www.twitter.com/home?status={{share_string}}%20{{request.build_absolute_url}}" class="btn btn-outline-primary">Twitter</a>
            </div>
        </div>  
    <div class="p-2">
            <div class="fb-comments" data-href="{{request.build_absolute_uri}}" data-width="" data-numposts="5"></div>
    </div>  
 </div>

{%endblock%}

src/posts/templates/posts/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Create Post:</h1>
    <form action="." method="POST" enctype='multipart/form-data'>
        {%csrf_token%}
        {{form}}
        <input type="submit" value="Submit">
    </form>
    <div>Go to <a href="{% url 'posts:posts_home'%}">home</a></div>
</body>
</html>

src/posts/templates/posts/index.html
<!DOCTYPE html> 
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'posts/css/style.css'%}">
    <title>Document</title>
    <style>
    </style>
</head>
<body>
    <h1>All The Index Is Listed Here</h1>
    <a href="{% url 'posts:posts_create' %}" style="display:block">Create New</a>
    <form action="." method="POST">
        {% csrf_token %}
        <input type="text" name='query' value={{search_value}}>
        <input type="submit" value="search">
    </form>
    {% if messages %}
    <ul class="messages">
       {% for message in messages%}
          <li {% if message.tags%} class="{{message.tags}}" {% endif%}>{{message}}</li>
       {% endfor %}
    </ul>
    {% endif%}
    {% for obj in obj_list%}
    <div class="col-md-6 mx-auto border border-success brder-2 m-2">
       <a href="{% url 'posts:posts_detail' slug=obj.slug%}" class="h1">{{obj.title}}</a>
       <p>{{obj.content|linebreaks|truncatewords:30}}</p>
       <img src="{% if obj.image %}{{obj.image.url}}{%endif%}" alt="" class="img-fluid">
       <div>
       <small>created:{{obj.timestamp}}</small>
       <small>last updated:{{obj.updated|timesince}}</small>
       <div class="p-2">
            <a href="{% url 'posts:posts_delete' slug=obj.slug%}" class="btn btn-danger">delete</a>
            <a href="{% url 'posts:posts_update' slug=obj.slug%}" class="btn btn-secondary">update</a>
       </div>
       </div>
    </div>
    {%endfor%}


    <div class="paginator">
        <span class="step-links">
            {% if obj_list.has_previous%}
               <a href="?page={{obj_list.previous_page_number}}">Previous</a>
            {% endif %}
            <span class="current">
                Page {{obj_list.number}} of {{obj_list.paginator.num_pages}}
            </span>
            {% if obj_list.has_next%}
                <a href="?page={{obj_list.next_page_number}}">Next</a>
            {% endif %}
        </span>
    </div>
    <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {%if not obj_list.has_previous%}
                <li class="page-item disabled">
                        <a class="page-link" href="." tabindex="-1" aria-disabled="true">Previous</a>
                </li>
                {%else%}
                <li class="page-item">
                        <a class="page-link" href="?page={{obj_list.previous_page_number}}&q={{searched_value}}" tabindex="-1" aria-disabled="true">Previous</a>
                </li>
                {% endif %}
              
              <li class="page-item"><a class="page-link" href="?page={{obj_list.number}}&q={{searched_value}}">{{obj_list.number}} of {{obj_list.paginator.num_pages}}</a></li>
              {% if obj_list.has_next%}
              <li class="page-item">
                    <a class="page-link" href="?page={{obj_list.next_page_number}}&q={{searched_value}}">Next</a>
              </li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{obj_list.paginator.num_pages}}&q={{searched_value}}">Next</a>
              </li>
            {%endif%}
            </ul>
    </nav>


















































<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>